services:
  rest:
    build:
      context: .
      dockerfile: ./apps/rest/Dockerfile
      target: development
    command: npm run start:dev rest
    env_file:
      - ./apps/rest/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
  csv:
    build:
      context: .
      dockerfile: ./apps/csv/Dockerfile
      target: development
    command: npm run start:dev csv
    env_file:
      - ./apps/csv/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3001:3001'
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data_micro:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - pgadmin_data_micro:/var/lib/pgadmin
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  postgres_data_micro:
  pgadmin_data_micro:
