apiVersion: v1
kind: Service
metadata:
  name: csv
spec:
  selector:
    app: csv
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csv
  labels:
    app: csv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: csv
  template:
    metadata:
      labels:
        app: csv
    spec:
      containers:
        - name: csv
          image: ghcr.io/primemb/csv:latest
          ports:
            - containerPort: 3000
          env:
            - name: RABBITMQ_URL
              value: 'amqp://rabbitmq:5672'
            - name: RABBITMQ_QUEUE
              value: storage
            - name: PORT
              value: '3000'
