apiVersion: v1
kind: Service
metadata:
  name: rest
spec:
  selector:
    app: rest
  type: LoadBalancer
  ports:
    - port: 3001
      targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest
  labels:
    app: rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      containers:
        - name: rest
          image: ghcr.io/primemb/rest:latest
          ports:
            - containerPort: 3001
          env:
            - name: RABBITMQ_URL
              value: 'amqp://rabbitmq:5672'
            - name: RABBITMQ_QUEUE
              value: storage
            - name: PORT
              value: '3001'
          imagePullPolicy: Always
