apiVersion: v1
kind: Service
metadata:
  name: storage
spec:
  selector:
    app: storage
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage
  labels:
    app: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: storage
          image: ghcr.io/primemb/storage:latest
          ports:
            - containerPort: 80 # Required by Kubernetes, but won't be used
          env:
            - name: DATABASE_URL_STORAGE
              value: 'postgresql://postgres:example@host.docker.internal:5432/storage?schema=public'
            - name: RABBITMQ_URL
              value: 'amqp://host.docker.internal:5672'
            - name: RABBITMQ_QUEUE
              value: 'storage'
          imagePullPolicy: Always
